"use client";
import { useEffect } from "react";
import { supabase } from "../lib/supabase";

export default function Home() {
  useEffect(() => {
    async function checkUser() {
      const { data: { session } } = await supabase.auth.getSession();
      if (session) window.location.href = "/mealplan";
    }
    checkUser();
  }, []);

  return (
    <main className="min-h-screen bg-[#FEFDF8]">

      {/* Hero section */}
      <section className="px-6 py-16 text-center max-w-2xl mx-auto">
        <div className="w-16 h-16 bg-[#2D6A4F] rounded-2xl flex items-center justify-center text-3xl mx-auto mb-6">
          🌿
        </div>
        <h1 className="text-5xl font-light text-[#2D6A4F] mb-4" style={{ fontFamily: "Georgia, serif" }}>
          Eatriv
        </h1>
        <p className="text-xl text-gray-500 mb-3 leading-relaxed">
          Stop guessing what to eat.
        </p>
        <p className="text-gray-400 mb-8 leading-relaxed">
          AI-powered meal plans, grocery lists and workout reminders — personalised to your body, goals and diet. Built for Nigerians and the world.
        </p>
        <div className="flex flex-col sm:flex-row gap-3 justify-center mb-4">
          <a href="/onboarding">
            <button className="bg-[#2D6A4F] text-white px-8 py-4 rounded-xl font-medium text-base hover:bg-[#235c43] transition-all w-full sm:w-auto">
              Get started free →
            </button>
          </a>
          <a href="/signup">
            <button className="border border-[#2D6A4F] text-[#2D6A4F] px-8 py-4 rounded-xl font-medium text-base hover:bg-[#F0FFF4] transition-all w-full sm:w-auto">
              Sign in
            </button>
          </a>
        </div>
        <p className="text-gray-400 text-sm">
          Free to start · ₦2,999/mo Pro · Cancel anytime
        </p>
      </section>

      {/* Features section */}
      <section className="px-6 py-12 bg-white">
        <div className="max-w-2xl mx-auto">
          <h2 className="text-2xl font-light text-center text-[#1A1A1A] mb-2" style={{ fontFamily: "Georgia, serif" }}>
            Everything you need to eat better
          </h2>
          <p className="text-center text-gray-400 text-sm mb-10">
            One app. All your nutrition needs covered.
          </p>
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
            {[
              { icon: "🤖", title: "AI Meal Plans", desc: "Get a personalised 7-day meal plan generated by AI — based on your goals, diet type, allergies and activity level." },
              { icon: "🛒", title: "Smart Grocery Lists", desc: "Every meal plan comes with a complete grocery list with exact quantities. Copy it and go shopping in minutes." },
              { icon: "💧", title: "Hydration Reminders", desc: "Never forget to drink water. Set custom reminders throughout the day to hit your 8 glasses daily goal." },
              { icon: "🔔", title: "Meal & Workout Alerts", desc: "Get reminded when it's time to eat, workout or drink water. Stay consistent without thinking about it." },
              { icon: "💪", title: "Workout Plans", desc: "Get a weekly workout plan matched to your goal — whether you want to lose weight, gain muscle or stay fit." },
              { icon: "📈", title: "Progress Tracking", desc: "Log your weight daily, track your streak and see your journey towards your goal weight on a visual chart." },
            ].map((f, i) => (
              <div key={i} className="border border-gray-100 rounded-2xl p-5 hover:border-[#B7E4C7] transition-all">
                <div className="text-2xl mb-3">{f.icon}</div>
                <div className="font-medium text-[#1A1A1A] mb-1">{f.title}</div>
                <div className="text-sm text-gray-400 leading-relaxed">{f.desc}</div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* How it works */}
      <section className="px-6 py-12 max-w-2xl mx-auto">
        <h2 className="text-2xl font-light text-center text-[#1A1A1A] mb-2" style={{ fontFamily: "Georgia, serif" }}>
          How Eatriv works
        </h2>
        <p className="text-center text-gray-400 text-sm mb-10">Ready in under 2 minutes</p>
        <div className="space-y-4">
          {[
            { step: "1", title: "Tell us about yourself", desc: "Answer 6 quick questions about your goals, body, diet and lifestyle." },
            { step: "2", title: "Get your AI meal plan", desc: "Our AI instantly generates a personalised 7-day meal plan with breakfast, lunch and dinner." },
            { step: "3", title: "Shop with your grocery list", desc: "Copy your auto-generated grocery list and shop for exactly what you need — nothing more." },
            { step: "4", title: "Stay on track with reminders", desc: "Set meal, water and workout reminders to keep you consistent every single day." },
          ].map((item, i) => (
            <div key={i} className="flex gap-4 items-start bg-white border border-gray-100 rounded-2xl p-4">
              <div className="w-10 h-10 rounded-full bg-[#2D6A4F] text-white flex items-center justify-center font-medium flex-shrink-0">
                {item.step}
              </div>
              <div>
                <div className="font-medium text-[#1A1A1A] mb-1">{item.title}</div>
                <div className="text-sm text-gray-400 leading-relaxed">{item.desc}</div>
              </div>
            </div>
          ))}
        </div>
      </section>

      {/* Pricing teaser */}
      <section className="px-6 py-12 bg-[#2D6A4F] text-white text-center">
        <div className="max-w-lg mx-auto">
          <h2 className="text-2xl font-light mb-3" style={{ fontFamily: "Georgia, serif" }}>
            Start free. Upgrade when ready.
          </h2>
          <p className="text-green-200 mb-6 text-sm leading-relaxed">
            Try Eatriv completely free. When you're ready for unlimited meal plans, reminders and workout plans — upgrade to Pro for just ₦2,999/month.
          </p>
          <a href="/onboarding">
            <button className="bg-white text-[#2D6A4F] px-8 py-4 rounded-xl font-medium text-base hover:bg-green-50 transition-all">
              Try Eatriv free →
            </button>
          </a>
          <p className="text-green-300 text-xs mt-4">No credit card required · Cancel anytime</p>
        </div>
      </section>

      {/* Footer */}
      <footer className="px-6 py-8 text-center bg-[#FEFDF8] border-t border-gray-100">
        <div className="text-xl font-light text-[#2D6A4F] mb-3" style={{ fontFamily: "Georgia, serif" }}>
          🌿 Eatriv
        </div>
        <p className="text-xs text-gray-400 mb-4">AI-powered nutrition coaching for everyone</p>
        <div className="flex gap-4 justify-center mb-4">
          <a href="/terms" className="text-xs text-gray-400 hover:text-[#2D6A4F] transition-all">Terms of Service</a>
          <a href="/privacy" className="text-xs text-gray-400 hover:text-[#2D6A4F] transition-all">Privacy Policy</a>
          <a href="/pricing" className="text-xs text-gray-400 hover:text-[#2D6A4F] transition-all">Pricing</a>
          <a href="mailto:eatrivapp@gmail.com" className="text-xs text-gray-400 hover:text-[#2D6A4F] transition-all">Contact</a>
        </div>
        <p className="text-xs text-gray-300">© 2026 Eatriv. Built with ❤️ in Nigeria 🇳🇬</p>
      </footer>

    </main>
  );
}